export const ADD_DECK = 'ADD_DECK';
export const RECEIVE_DECKS = 'RECEIVE_DECKS';
export const DELETE_ALL_DECKS = 'DELETE_ALL_DECKS';
export const ADD_CARD = 'ADD_CARD';
export const ADD_HISTORY_ENTRY = 'ADD_HISTORY_ENTRY';
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';
